[project]
name = "pdf2text"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.1",
    "pdfplumber>=0.11.6",
    "pymupdf>=1.25.5",
]
